<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPRURYAW0103" name="test.quadrate.QuadrateTest" tests="9" failures="1" timestamp="9 Nov 2015 15:57:33 GMT" time="0.013" errors="0">
  <testcase name="quadrateLengthTest" time="0.002" classname="test.quadrate.QuadrateTest">
    <failure type="java.lang.AssertionError" message="For side = 0.0
The test fails, the length or the number of decimal places does not match expected [0.0] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: For side = 0.0
The test fails, the length or the number of decimal places does not match expected [0.0] but found [-1.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at test.quadrate.QuadrateTest.quadrateLengthTest(QuadrateTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- quadrateLengthTest -->
  <testcase name="quadrateAreaTest" time="0.007" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateLengthTest" time="0.001" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateAreaTest" time="0.001" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateAreaTest" time="0.001" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateLengthTest" time="0.000" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateConstructorTest" time="0.000" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateConstructorTest" time="0.000" classname="test.quadrate.QuadrateTest"/>
  <testcase name="quadrateConstructorTest" time="0.001" classname="test.quadrate.QuadrateTest"/>
</testsuite> <!-- test.quadrate.QuadrateTest -->
